version: '3.8'

services:
  api:
    build: .
    restart: always
    ports:
      - 8057:8080
    depends_on:
      - celeryworker
    environment:
      - REDIS_URI=redis://redis
    env_file:
      - .env
  
  celeryworker:
    build: .
    restart: always
    depends_on:
      - redis
    command: ["celery", "-A","src.agent.celery_app","worker","--loglevel=info","-E"]
    env_file:
      - .env
    environment:
      - REDIS_URI=redis://redis

  redis:
    image: redis:latest
    restart: always