version: "3.8"

services:
  web:
    build: .
    ports:
      - 8001:8000
      - 5556:5555
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    
    

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A src.agent.celery_app worker --loglevel=info -E
    volumes:
      - .:/app
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    depends_on:
      - redis
      - web

  # celerybackend:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   healthcheck:
  #     test: [ "CMD", "redis-cli", "ping" ]
  #     interval: 5s
  #     timeout: 30s
  #     retries: 50
  #   restart: always